@baseUrl = https://localhost:7090

### Get All Specializations
GET {{baseUrl}}/api/Appointments/getAllSpecializations
Accept: application/json

### Get Doctors By Specialization
POST {{baseUrl}}/api/Appointments/getDoctorsBySpecialization
Content-Type: application/json

{
  "specializationID": "dc5a5e3c-1706-4ba3-843f-0cf7a20a09ed"
}

### Get Available Dates and Times By Doctor ID
POST {{baseUrl}}/api/Appointments/GetAvailableDatesAndTimesByDoctorID
Content-Type: application/json

{
  "doctorID": "1327a54b-948c-4640-af15-2c7147ee8076"
}
