// <auto-generated />
using System;
using AP_clinical_system.Models.sql_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP_clinical_system.Models.sql_Context.Migrations
{
    [DbContext(typeof(AP_Context))]
    [Migration("20260421210614_ModelUpdateForNullable")]
    partial class ModelUpdateForNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP_clinical_system.Models.Entities.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("appointment_status")
                        .HasColumnType("int");

                    b.Property<int?>("appointment_time_slot")
                        .HasColumnType("int");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("receptionist_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("receptionist_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.autonumber", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("entity_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("last_number")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("pattern")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("autonumbers");

                    b.HasData(
                        new
                        {
                            id = new Guid("c2ca50d2-5d07-44bd-b276-dbeaa3be35d2"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "appointment",
                            field_name = "appointment_no",
                            last_number = 1,
                            pattern = "APP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("4ea131a1-69a8-4b16-b378-f3f8ab68aab7"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "clinic_manager_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "CMI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("4f22e6eb-35b7-46c3-ba05-e5ad8c079142"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("b91bf242-b386-4df3-8cdf-9843b5874699"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information_specialization_mtm",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DIS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("34186f8c-36bc-4846-8532-356d87d6ff5e"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_leave",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DLV-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("53ff12ad-3d2e-49c6-8043-ec5ba79940fd"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_schedule",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSC-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("32bec5fd-5b47-4c55-a67f-dfe1abef7a3c"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_specialization",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("c463e8b8-3d2d-4584-9807-a3bf41aa5678"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "notification",
                            field_name = "notification_no",
                            last_number = 1,
                            pattern = "NOTI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("286bb02d-a01c-4895-a77d-15aebccc7af2"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "patient_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "PINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("8bc1ec1d-60e6-4b10-a083-1d7993ec2602"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "prescription",
                            field_name = "prescription_no",
                            last_number = 1,
                            pattern = "PRS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("746d4975-4013-4ff3-abde-dff8f4bbe554"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "receptionist_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "RINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("a4fb3154-6358-444f-a8fe-3e4d9e829ec2"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "system_user",
                            field_name = "user_no",
                            last_number = 1,
                            pattern = "USR-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("0635f853-0267-4160-bd20-058936353d4a"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "visit_record",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "VR-{0:D5}"
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.clinic_manager_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("clinic_manager_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("doctor_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information_specialization_mtm", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("doctor_specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_information_specialization_mtms");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_leave", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("leave_type")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("doctor_leaves");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("friday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("monday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_schedules");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_specialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_specializations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("notification_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.patient_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("patient_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("medicine_dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_frequency_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.receptionist_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("receptionist_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.system_user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_role")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("system_users");

                    b.HasData(
                        new
                        {
                            id = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            cpr = "040400069",
                            createdby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "abbasfadhel499@gmail.com",
                            firt_name = "Abbas",
                            hashed_password = "123",
                            inactive = false,
                            last_name = "Aljamri",
                            modifiedby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            modifiedon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            phone_number = "34309097",
                            user_no = "USR-00001",
                            user_role = 1000
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.visit_record", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescribed_treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("visit_records");
                });
#pragma warning restore 612, 618
        }
    }
}
