// <auto-generated />
using System;
using AP_clinical_system.Models.sql_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP_clinical_system.Models.sql_Context.Migrations
{
    [DbContext(typeof(AP_Context))]
    [Migration("20260421210542_Auto_20260422_000536")]
    partial class Auto_20260422_000536
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP_clinical_system.Models.Entities.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("appointment_status")
                        .HasColumnType("int");

                    b.Property<int?>("appointment_time_slot")
                        .HasColumnType("int");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("receptionist_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("receptionist_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.autonumber", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("entity_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("last_number")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("pattern")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("autonumbers");

                    b.HasData(
                        new
                        {
                            id = new Guid("30eef465-6d4d-4475-8727-275cd0921f93"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "appointment",
                            field_name = "appointment_no",
                            last_number = 1,
                            pattern = "APP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("82469d6c-8faa-4f85-9b92-6fa9575f61d7"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "clinic_manager_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "CMI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("a5c3c6b3-bb6b-47e9-8515-29e47b492c2f"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("66ed2675-98e1-4815-bdaf-16496b6a534c"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information_specialization_mtm",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DIS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("9dec2755-2918-4950-817a-64d6a8dae85e"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_leave",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DLV-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("7da00435-11e7-4598-8c52-a08e6d77b708"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_schedule",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSC-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("4cbe14a0-bbe2-44b2-ad91-c96784254da9"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_specialization",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("0d7c1b0e-4193-4324-8aec-3a4ecb9ee8ac"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "notification",
                            field_name = "notification_no",
                            last_number = 1,
                            pattern = "NOTI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("f0707724-b3d5-4d12-86bd-ad6cb3770b0f"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "patient_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "PINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("93c59830-9e39-492c-a974-3015a4bb10c6"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "prescription",
                            field_name = "prescription_no",
                            last_number = 1,
                            pattern = "PRS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("79b76ba8-04cb-45f3-9eba-d40bbcdb0a18"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "receptionist_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "RINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("c3867cc9-a345-4868-bd21-95f4b4fe2a45"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "system_user",
                            field_name = "user_no",
                            last_number = 1,
                            pattern = "USR-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("89742bd2-f218-4600-a76c-6986a74713d2"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "visit_record",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "VR-{0:D5}"
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.clinic_manager_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("clinic_manager_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("doctor_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information_specialization_mtm", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("doctor_specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_information_specialization_mtms");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_leave", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("leave_type")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("doctor_leaves");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("friday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("monday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_schedules");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_specialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_specializations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("notification_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.patient_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("patient_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("medicine_dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_frequency_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.receptionist_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("receptionist_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.system_user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_role")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("system_users");

                    b.HasData(
                        new
                        {
                            id = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            cpr = "040400069",
                            createdby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "abbasfadhel499@gmail.com",
                            firt_name = "Abbas",
                            hashed_password = "123",
                            inactive = false,
                            last_name = "Aljamri",
                            modifiedby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            modifiedon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            phone_number = "34309097",
                            user_no = "USR-00001",
                            user_role = 1000
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.visit_record", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescribed_treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("visit_records");
                });
#pragma warning restore 612, 618
        }
    }
}
