// <auto-generated />
using System;
using AP_clinical_system.Models.sql_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP_clinical_system.Models.sql_Context.Migrations
{
    [DbContext(typeof(AP_Context))]
    [Migration("20260421205443_Auto_20260421_235438")]
    partial class Auto_20260421_235438
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP_clinical_system.Models.Entities.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("appointment_status")
                        .HasColumnType("int");

                    b.Property<int>("appointment_time_slot")
                        .HasColumnType("int");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("doctor_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("receptionist_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("receptionist_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specialization_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.autonumber", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("entity_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int>("last_number")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("autonumbers");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.clinic_manager_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("clinic_manager_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("doctor_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information_specialization_mtm", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("doctor_specialization_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_information_specialization_mtms");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_leave", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int>("leave_type")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("doctor_leaves");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("friday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("monday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_schedules");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_specialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_specializations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("notification_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.patient_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("patient_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("medicine_dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_frequency_duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.receptionist_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("receptionist_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.system_user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firt_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_role")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("system_users");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.visit_record", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescribed_treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("visit_records");
                });
#pragma warning restore 612, 618
        }
    }
}
