// <auto-generated />
using System;
using AP_clinical_system.Models.sql_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP_clinical_system.Models.sql_Context.Migrations
{
    [DbContext(typeof(AP_Context))]
    [Migration("20260430062222_AddIdentityRoles")]
    partial class AddIdentityRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP_clinical_system.Models.Entities.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("appointment_status")
                        .HasColumnType("int");

                    b.Property<int?>("appointment_time_slot")
                        .HasColumnType("int");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("receptionist_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("receptionist_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.autonumber", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("entity_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("last_number")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("pattern")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("autonumbers");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.clinic_manager_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("clinic_manager_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("doctor_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information_specialization_mtm", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("doctor_specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_information_specialization_mtms");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_leave", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("leave_type")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("doctor_leaves");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("friday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("monday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_schedules");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_specialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_specializations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("notification_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.patient_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("patient_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("medicine_dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_frequency_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.receptionist_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("receptionist_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.system_user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_role")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("system_users");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.visit_record", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescribed_treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("visit_records");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
