// <auto-generated />
using System;
using AP_clinical_system.Models.sql_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP_clinical_system.Models.sql_Context.Migrations
{
    [DbContext(typeof(AP_Context))]
    [Migration("20260421210708_Auto_20260422_000703")]
    partial class Auto_20260422_000703
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP_clinical_system.Models.Entities.appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appointment_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("appointment_status")
                        .HasColumnType("int");

                    b.Property<int?>("appointment_time_slot")
                        .HasColumnType("int");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("date")
                        .HasColumnType("date");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("receptionist_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("receptionist_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.autonumber", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("entity_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("field_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("last_number")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("pattern")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("autonumbers");

                    b.HasData(
                        new
                        {
                            id = new Guid("7143b283-51c6-4199-83bf-195444dcafef"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "appointment",
                            field_name = "appointment_no",
                            last_number = 1,
                            pattern = "APP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("f370d4bc-36c4-4611-9d78-5ed538759cfb"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "clinic_manager_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "CMI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("5b7ea96f-7e25-41ac-8873-77fb6d3c1b4c"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("c2c16474-bda4-4526-b8e6-4c441dd1b940"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_information_specialization_mtm",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DIS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("b293bac4-3997-4872-8a2e-ea18c9c01e94"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_leave",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DLV-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("051aad61-f034-491f-ae19-cdf968b8bd0d"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_schedule",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSC-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("0b01d7ec-f488-4ab7-8b0d-8ff8955b7fba"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "doctor_specialization",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "DSP-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("f96801e9-ac6a-4d93-9dd7-867f42432256"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "notification",
                            field_name = "notification_no",
                            last_number = 1,
                            pattern = "NOTI-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("4a6395ca-bdf7-4155-b6ca-843423ae5687"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "patient_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "PINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("e5a41fff-c4df-46a7-9c07-11f1f4b520bb"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "prescription",
                            field_name = "prescription_no",
                            last_number = 1,
                            pattern = "PRS-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("1dcf32bc-1ef7-49d0-8e00-857e9db799e9"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "receptionist_information",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "RINF-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("ca0aefb2-0e68-49c5-86ac-dd7276004c7b"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "system_user",
                            field_name = "user_no",
                            last_number = 1,
                            pattern = "USR-{0:D5}"
                        },
                        new
                        {
                            id = new Guid("0fbb23e9-3541-48c5-a17c-d5acc2edd91d"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            entity_name = "visit_record",
                            field_name = "record_no",
                            last_number = 1,
                            pattern = "VR-{0:D5}"
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.clinic_manager_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("clinic_manager_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("doctor_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_information_specialization_mtm", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("doctor_specialization_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_specialization_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_information_specialization_mtms");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_leave", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("leave_type")
                        .HasColumnType("int");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("doctor_leaves");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_schedule", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_information_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_information_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("friday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("friday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("monday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("monday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saturday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sunday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thursday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wednesday_start")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_schedules");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.doctor_specialization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specialization_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("doctor_specializations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.notification", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("notification_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.patient_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("patient_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("doctor_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("doctor_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("medicine_dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_frequency_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicine_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("patient_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("patient_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("prescription_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("prescriptions");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.receptionist_information", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("system_user_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("system_user_ref")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.ToTable("receptionist_informations");
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.system_user", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashed_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("user_role")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("system_users");

                    b.HasData(
                        new
                        {
                            id = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            cpr = "040400069",
                            createdby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            createdon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            email = "abbasfadhel499@gmail.com",
                            firt_name = "Abbas",
                            hashed_password = "123",
                            inactive = false,
                            last_name = "Aljamri",
                            modifiedby = new Guid("b9c9f28d-19df-4c31-92f7-5ebd7e5dc8d1"),
                            modifiedon = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            phone_number = "34309097",
                            user_no = "USR-00001",
                            user_role = 1000
                        });
                });

            modelBuilder.Entity("AP_clinical_system.Models.Entities.visit_record", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("appointment_lookup_to")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("appointment_ref")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("createdby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doctor_notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("modifiedby")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<string>("prescribed_treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("record_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("visit_records");
                });
#pragma warning restore 612, 618
        }
    }
}
